// src/svelte/Link.svelte
<script>
  import { history } from '../core';
  
  export let to;
  export let rel = '';
  export let replace = false;
  export let meta = {};

  function handleClick(event) {
    if (to) {
      const action = replace ? history.replace : history.push;
      action({ to, meta });
    }
  }
</script>

<a href={to} {rel} on:click on:click|preventDefault={handleClick}>
  <slot />
</a>

// src/react/Link/index.jsx
import React from 'react';
import { history } from '../../core';

function Link({ children, to, meta = {}, replace = false, onClick, ...other }) {
  function handleClick(event) {
    event.preventDefault();

    if (to) {
      const action = replace ? history.replace : history.push;

      action({ to, meta });

      if (typeof onClick === 'function') {
        onClick(event);
      }
    }
  }

  return (
    <a {...other} href={to} onClick={handleClick}>{children}</a>
  );
}

export default Link;
