// src/svelte/Link.svelte
<script>
  import { history } from '../core';
  
  export let to;
  export let rel = '';
  export let replace = false;
  export let meta = {};

  function handleClick(event) {
    if (to) {
      const action = replace ? history.replace : history.push;
      action({ to, meta });
    }
  }
</script>

<a href={to} {rel} on:click on:click|preventDefault={handleClick}>
  <slot />
</a>

// src/react/Link.jsx
import React from 'react';
import useHistory from './useHistory';

function Link({ to, state = {}, onClick, ...otherProps }) {
  const history = useHistory();

  function handleClick(event) {
    event.preventDefault();

    history.push(to, state);

    onClick && onClick(event);
  }

  return (
    <a {...otherProps} href={to} onClick={handleClick} />
  );
}

export default Link;
